name: project_for_class
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_ui_auth: ^1.1.15
  google_sign_in: ^6.0.2
  firebase_ui_oauth_google: ^1.0.22
  cloud_firestore: ^4.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  tuple: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - images/Logo-NBA.png
    - images/mlbLogo.png
    - images/mlsCrestLogo.png
    - images/nflLogo.png
    - images/flame-success.png